package com.example.visuallyimpaired.Utility;

public class Constants {

    public final static String WELCOME_MSG = "WELCOME TO PERSONAL DIARY APP,CLICK ANY SIDE OF THE SCREEN TO USE THE RESPECTIVE FEATURE,";
    public final static String CONTACT_SPEAK = "YOU HAVE CLICK CONTACT SECTION,CLICK AGAIN TO PROCEED FURTHER";
    public final static String MESSAGE_SPEAK = "YOU HAVE CLICK MESSAGE SECTION,CLICK AGAIN TO PROCEED FURTHER";
    public final static String PEOPLE_SPEAK = "YOU HAVE CLICK PEOPLE SECTION,CLICK AGAIN TO PROCEED FURTHER";
    public final static String BATTERY_SPEAK = "YOU HAVE CLICK BATTERY SECTION,CLICK AGAIN TO PROCEED FURTHER";
    public final static String ANALYSIS_SPEAK = "YOU HAVE CLICK SURROUNDING ANALYSIS SECTION,CLICK AGAIN TO PROCEED FURTHER";
    public final static String COMPOSE_MSG = "AFTER YOU FINISH WRITING MESSAGE,YOU CAN LONG PRESS ANYWHERE ON THE SCREEN TO KNOWN WHAT MESSAGE YOU HAVE WRITTEN,";
    public final static String CONTACT_MSG = "AFTER YOU FINISH WRITING NUMBER,YOU CAN LONG PRESS ANYWHERE ON THE SCREEN TO KNOWN WHAT NUMBER YOU HAVE WRITTEN,";
    public final static String TAB_MSG_1 = "SWIPE RIGHT TO VIEW CALL LOGS AND THEN SWIPE RIGHT AGAIN TO MAKE A CALL\nLong Press Any Contact To Compose A Message To That Respective Contact";
    public final static String TAB_MSG_2 = "SWIPE LEFT TO VIEW CONTACTS AND SWIPE RIGHT TO MAKE A CALL";
    public final static String TAB_MSG_3 = "SWIPE LEFT TO VIEW CALL LOGS AND THEN SWIPE LEFT AGAIN TO VIEW CONTACTS," + CONTACT_MSG;
    public final static String TAB_MSG = "SWIPE RIGHT TO VIEW CALL LOGS AND THEN SWIPE RIGHT AGAIN TO MAKE A CALL\nLong Press Any Contact To Compose A Message To That Respective Contact";
    public final static String GO_BACK_MESSAGE = "SHAKE YOUR PHONE TO GO BACK";
    public final static String SEND_MSG = "DOUBLE TAP ANYWHERE ON THE SCREEN TO SEND MESSAGE";
    public final static String MSG = "LONG PRESS ANYWHERE ON THE SCREEN TO COMPOSE A NEW MESSAGE";
    public final static String PERSON_SCREEN_INFO = "DOUBLE TAP ON UPPER PART OF THE SCREEN TO ADD PERSON OR DOUBLE TAP ON LOWER PART OF THE SCREEN TO DETECT PERSON"+GO_BACK_MESSAGE;
    public final static String ADD_PERSON = "FACE DETECTED,FOCUS IS ON NAME TEXT BOX AFTER ENTERING NAME DOUBLE TAP ANYWHERE ON THE SCREEN TO SAVE THE PERSON."+GO_BACK_MESSAGE;
    public final static String ADD_PERSON_TO_CONTINUE = " YOU HAVE TO ADD FACES FOR USING PERSON DETECTION FEATURE";
    public final static String DETECT_OBJ = "\nTO REPEAT THE RESULT DOUBLE TAP ANYWHERE ON THE SCREEN AND TO CLICK IMAGE AGAIN LONG PRESS ANYWHERE ON THE SCREEN OR "+GO_BACK_MESSAGE;
}

